[project]
name = "spectrum"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.4.2",
    "pandas>=3.0.0",
]

[tool.uv.workspace]
members = ["packages/*"]
exclude = ["packages/frontend"]

[tool.coverage.report]
exclude_also = [
    "def to_string",
    "def __repr__",
    "def __str__",
    "if __name__ == '__main__'",
    "raise NotImplementedError",
    "if TYPE_CHECKING",
]
