[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiofiles>=25.1.0",
    "alembic>=1.16.4",
    "boto3>=1.40.55",
    "boto3-stubs[s3]>=1.40.55",
    "celery-types>=0.23.0",
    "celery[redis]>=5.5.3",
    "eggp>=1.0.6",
    "fastapi[standard]>=0.116.1",
    "loguru>=0.7.3",
    "numpy>=2.3.2",
    "pandas>=2.3.1",
    "pandas-stubs>=2.3.0.250703",
    "psycopg2-binary>=2.9.10",
    "python-dotenv>=1.1.1",
    "python-multipart>=0.0.20",
    "reggression>=1.0.8",
    "requests>=2.32.5",
    "s3fs>=0.4.2",
    "sqlalchemy>=2.0.41",
    "sqlmodel>=0.0.24",
    "types-aiofiles>=25.1.0.20251011",
    "types-requests>=2.32.4.20250913",
    "uvicorn>=0.35.0",
    "watchtower>=3.4.0",
    "websockets>=15.0.1",
]
