"""adds SR model ORM

Revision ID: 03b983320b6c
Revises: 72217dc2bbb9
Create Date: 2026-03-20 18:50:20.055725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03b983320b6c'
down_revision: Union[str, Sequence[str], None] = '72217dc2bbb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('models',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('model_path', sa.String(), nullable=False),
    sa.Column('profile_version_id', sa.UUID(), nullable=False),
    sa.Column('dataset_version_id', sa.UUID(), nullable=False),
    sa.Column('dataset_artifact_id', sa.UUID(), nullable=False),
    sa.Column('generated_by', sa.UUID(), nullable=False),
    sa.Column('owner', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dataset_artifact_id'], ['dataset_artifacts.id'], name=op.f('fk_models_dataset_artifact_id_dataset_artifacts')),
    sa.ForeignKeyConstraint(['dataset_version_id'], ['dataset_versions.id'], name=op.f('fk_models_dataset_version_id_dataset_versions')),
    sa.ForeignKeyConstraint(['generated_by'], ['jobs.id'], name=op.f('fk_models_generated_by_jobs')),
    sa.ForeignKeyConstraint(['owner'], ['owners.id'], name=op.f('fk_models_owner_owners')),
    sa.ForeignKeyConstraint(['profile_version_id'], ['profile_versions.id'], name=op.f('fk_models_profile_version_id_profile_versions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_models')),
    sa.UniqueConstraint('id', name='uq_models_id')
    )
    op.create_index('idx_models_timestamp', 'models', ['timestamp'], unique=False)
    op.create_unique_constraint('uq_job_runs_id', 'job_runs', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_job_runs_id', 'job_runs', type_='unique')
    op.drop_index('idx_models_timestamp', table_name='models')
    op.drop_table('models')
    # ### end Alembic commands ###
