"""adds indexes to profiles

Revision ID: 077bd466df64
Revises: e863ebe1ac4f
Create Date: 2026-03-05 22:02:46.779735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '077bd466df64'
down_revision: Union[str, Sequence[str], None] = 'e863ebe1ac4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_profiles_owner_id', 'profiles', ['owner_id'], unique=False)
    op.create_index('ix_profiles_owner_visibility', 'profiles', ['owner_id', 'visibility'], unique=False)
    op.create_index('ix_profiles_status', 'profiles', ['status'], unique=False)
    op.create_index('ix_profiles_visibility', 'profiles', ['visibility'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_profiles_visibility', table_name='profiles')
    op.drop_index('ix_profiles_status', table_name='profiles')
    op.drop_index('ix_profiles_owner_visibility', table_name='profiles')
    op.drop_index('ix_profiles_owner_id', table_name='profiles')
    # ### end Alembic commands ###
