"""adds owner_id to refresh token

Revision ID: 07d8d0d3f085
Revises: 66bae0e84cd7
Create Date: 2026-03-08 02:05:55.166402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '07d8d0d3f085'
down_revision: Union[str, Sequence[str], None] = '66bae0e84cd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dataset_artifacts', sa.Column('version', sa.Integer(), nullable=False))
    op.add_column('dataset_artifacts', sa.Column('is_latest', sa.Boolean(), nullable=False))
    op.create_index('idx_dataset_artifacts_id_version', 'dataset_artifacts', ['id', 'version'], unique=False)
    op.create_index('idx_dataset_artifacts_is_latest', 'dataset_artifacts', ['is_latest'], unique=False)
    op.create_index('idx_dataset_artifacts_latest', 'dataset_artifacts', ['id'], unique=True, postgresql_where=sa.text('is_latest = true'))
    op.create_unique_constraint('uq_dataset_artifacts_id_version', 'dataset_artifacts', ['id', 'version'])
    op.create_index('idx_dataset_versions_id_version', 'dataset_versions', ['id', 'version'], unique=False)
    op.create_index('idx_dataset_versions_is_latest', 'dataset_versions', ['is_latest'], unique=False)
    op.create_index('idx_dataset_versions_latest', 'dataset_versions', ['id'], unique=True, postgresql_where=sa.text('is_latest = true'))
    op.add_column('datasets', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('datasets', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('datasets', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_column('datasets', 'timestamp')
    op.create_index('idx_owners_id_version', 'owners', ['id', 'version'], unique=False)
    op.create_index('idx_owners_is_latest', 'owners', ['is_latest'], unique=False)
    op.create_index('idx_owners_latest', 'owners', ['id'], unique=True, postgresql_where=sa.text('is_latest = true'))
    op.add_column('profile_dataset_versions', sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False))
    op.add_column('profile_dataset_versions', sa.Column('version', sa.Integer(), nullable=False))
    op.add_column('profile_dataset_versions', sa.Column('is_latest', sa.Boolean(), nullable=False))
    op.add_column('profile_dataset_versions', sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index('idx_profile_dataset_versions_id_version', 'profile_dataset_versions', ['id', 'version'], unique=False)
    op.create_index('idx_profile_dataset_versions_is_latest', 'profile_dataset_versions', ['is_latest'], unique=False)
    op.create_index('idx_profile_dataset_versions_latest', 'profile_dataset_versions', ['id'], unique=True, postgresql_where=sa.text('is_latest = true'))
    op.create_unique_constraint('uq_profile_dataset_versions_id_version', 'profile_dataset_versions', ['id', 'version'])
    op.create_index('idx_profiles_id_version', 'profiles', ['id', 'version'], unique=False)
    op.create_index('idx_profiles_is_latest', 'profiles', ['is_latest'], unique=False)
    op.create_index('idx_profiles_latest', 'profiles', ['id'], unique=True, postgresql_where=sa.text('is_latest = true'))
    op.add_column('refresh_tokens', sa.Column('owner_id', sa.UUID(), nullable=False))
    op.create_foreign_key(op.f('fk_refresh_tokens_owner_id_owners'), 'refresh_tokens', 'owners', ['owner_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_refresh_tokens_owner_id_owners'), 'refresh_tokens', type_='foreignkey')
    op.drop_column('refresh_tokens', 'owner_id')
    op.drop_index('idx_profiles_latest', table_name='profiles', postgresql_where=sa.text('is_latest = true'))
    op.drop_index('idx_profiles_is_latest', table_name='profiles')
    op.drop_index('idx_profiles_id_version', table_name='profiles')
    op.drop_constraint('uq_profile_dataset_versions_id_version', 'profile_dataset_versions', type_='unique')
    op.drop_index('idx_profile_dataset_versions_latest', table_name='profile_dataset_versions', postgresql_where=sa.text('is_latest = true'))
    op.drop_index('idx_profile_dataset_versions_is_latest', table_name='profile_dataset_versions')
    op.drop_index('idx_profile_dataset_versions_id_version', table_name='profile_dataset_versions')
    op.drop_column('profile_dataset_versions', 'timestamp')
    op.drop_column('profile_dataset_versions', 'is_latest')
    op.drop_column('profile_dataset_versions', 'version')
    op.drop_column('profile_dataset_versions', 'id')
    op.drop_index('idx_owners_latest', table_name='owners', postgresql_where=sa.text('is_latest = true'))
    op.drop_index('idx_owners_is_latest', table_name='owners')
    op.drop_index('idx_owners_id_version', table_name='owners')
    op.add_column('datasets', sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_column('datasets', 'updated_at')
    op.drop_column('datasets', 'created_at')
    op.drop_column('datasets', 'deleted_at')
    op.drop_index('idx_dataset_versions_latest', table_name='dataset_versions', postgresql_where=sa.text('is_latest = true'))
    op.drop_index('idx_dataset_versions_is_latest', table_name='dataset_versions')
    op.drop_index('idx_dataset_versions_id_version', table_name='dataset_versions')
    op.drop_constraint('uq_dataset_artifacts_id_version', 'dataset_artifacts', type_='unique')
    op.drop_index('idx_dataset_artifacts_latest', table_name='dataset_artifacts', postgresql_where=sa.text('is_latest = true'))
    op.drop_index('idx_dataset_artifacts_is_latest', table_name='dataset_artifacts')
    op.drop_index('idx_dataset_artifacts_id_version', table_name='dataset_artifacts')
    op.drop_column('dataset_artifacts', 'is_latest')
    op.drop_column('dataset_artifacts', 'version')
    # ### end Alembic commands ###
