"""converts Job and Model relationship to be 1:1

Revision ID: 097789793cca
Revises: a3ee514115bb
Create Date: 2026-02-15 11:53:35.264092

"""
from typing import Sequence, Union

from alembic import op
# import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '097789793cca'
down_revision: Union[str, Sequence[str], None] = 'a3ee514115bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'models', ['job_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'models', type_='unique')  # type: ignore
    # ### end Alembic commands ###
