"""adds relationship between job and dataset

Revision ID: 1b4c0c121141
Revises: 25f196bcb032
Create Date: 2026-02-06 14:03:31.571950

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '1b4c0c121141'
down_revision: Union[str, Sequence[str], None] = '25f196bcb032'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key("fk_jobs_dataset_id_datasets", 'jobs', 'datasets', [
                          'dataset_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_jobs_dataset_id_datasets",
                       'jobs', type_='foreignkey')
    # ### end Alembic commands ###
