"""creates base model for all ORM models

Revision ID: 1f00da4a89d7
Revises: 1244e334e12f
Create Date: 2026-02-17 19:29:05.478953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f00da4a89d7'
down_revision: Union[str, Sequence[str], None] = '1244e334e12f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_runs', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('jobs', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'updated_at')
    op.drop_column('job_runs', 'updated_at')
    # ### end Alembic commands ###
