"""moves profile data to profile version

Revision ID: 24ac61ceab4d
Revises: 8d96f7204c5a
Create Date: 2026-03-11 22:43:40.728972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '24ac61ceab4d'
down_revision: Union[str, Sequence[str], None] = '8d96f7204c5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

profile_status = sa.Enum('ACTIVE', 'INACTIVE',
                         'DELETED', name='profilestatus')
profile_visibility = sa.Enum('PUBLIC', 'PRIVATE', name='profilevisibility')


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    profile_status.create(op.get_bind())
    profile_visibility.create(op.get_bind())

    op.create_unique_constraint(
        'uq_profile_dataset_associations_id', 'profile_dataset_associations', ['id'])
    op.add_column('profile_versions', sa.Column(
        'name', sa.String(length=255), nullable=False))
    op.add_column('profile_versions', sa.Column(
        'description', sa.Text(), nullable=True))
    op.add_column('profile_versions', sa.Column(
        'status', profile_status, nullable=False))
    op.add_column('profile_versions', sa.Column(
        'visibility', profile_visibility, nullable=False))
    op.drop_column('profiles', 'status')
    op.drop_column('profiles', 'name')
    op.drop_column('profiles', 'description')
    op.drop_column('profiles', 'visibility')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('visibility', postgresql.ENUM(
        'PUBLIC', 'PRIVATE', name='profile_visibility'), autoincrement=False, nullable=False))
    op.add_column('profiles', sa.Column(
        'description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('profiles', sa.Column('name', sa.VARCHAR(
        length=255), autoincrement=False, nullable=False))
    op.add_column('profiles', sa.Column('status', postgresql.ENUM(
        'ACTIVE', 'INACTIVE', 'DELETED', name='profile_status'), autoincrement=False, nullable=False))
    op.drop_column('profile_versions', 'visibility')
    op.drop_column('profile_versions', 'status')
    op.drop_column('profile_versions', 'description')
    op.drop_column('profile_versions', 'name')
    op.drop_constraint('uq_profile_dataset_associations_id',
                       'profile_dataset_associations', type_='unique')
    # ### end Alembic commands ###
