"""adds DatasetArtifactVersion model

Revision ID: 3563f9e799d3
Revises: 07d8d0d3f085
Create Date: 2026-03-08 12:24:21.125079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.sql.sqltypes import Enum as SAEnum

# revision identifiers, used by Alembic.
revision: str = '3563f9e799d3'
down_revision: Union[str, Sequence[str], None] = '07d8d0d3f085'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

artifact_type_enum: SAEnum = postgresql.ENUM(
    'DATA', 'SCHEMA', 'STATS', 'PREVIEW', 'FEATURES', 'MANIFEST', name='artifacttype', create_type=False)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE artifacttype ADD VALUE IF NOT EXISTS 'MANIFEST'")

    op.create_table('dataset_version_artifacts',
                    sa.Column('dataset_version_id', sa.UUID(), nullable=False),
                    sa.Column('dataset_artifact_id',
                              sa.UUID(), nullable=False),
                    sa.Column('artifact_type',
                              artifact_type_enum, nullable=False),
                    sa.Column('id', sa.UUID(), server_default=sa.text(
                        'gen_random_uuid()'), nullable=False),
                    sa.Column('version', sa.Integer(), nullable=False),
                    sa.Column('is_latest', sa.Boolean(), nullable=False),
                    sa.Column('timestamp', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.ForeignKeyConstraint(['dataset_artifact_id'], ['dataset_artifacts.id'], name=op.f(
                        'fk_dataset_version_artifacts_dataset_artifact_id_dataset_artifacts')),
                    sa.ForeignKeyConstraint(['dataset_version_id'], ['dataset_versions.id'], name=op.f(
                        'fk_dataset_version_artifacts_dataset_version_id_dataset_versions')),
                    sa.PrimaryKeyConstraint('id', 'version', name=op.f(
                        'pk_dataset_version_artifacts')),
                    sa.UniqueConstraint('dataset_version_id', 'artifact_type', name=op.f(
                        'uq_dataset_version_artifacts_dataset_version_id')),
                    sa.UniqueConstraint(
                        'id', 'version', name='uq_dataset_version_artifacts_id_version')
                    )
    op.create_index('idx_dataset_version_artifacts_id_version',
                    'dataset_version_artifacts', ['id', 'version'], unique=False)
    op.create_index('idx_dataset_version_artifacts_is_latest',
                    'dataset_version_artifacts', ['is_latest'], unique=False)
    op.create_index('idx_dataset_version_artifacts_latest', 'dataset_version_artifacts', [
                    'id'], unique=True, postgresql_where=sa.text('is_latest = true'))
    op.create_unique_constraint(
        op.f('uq_dataset_artifacts_checksum'), 'dataset_artifacts', ['checksum'])
    op.drop_constraint(op.f('fk_dataset_artifacts_dataset_version_id_dataset_versions'),
                       'dataset_artifacts', type_='foreignkey')
    op.drop_column('dataset_artifacts', 'artifact_type')
    op.drop_column('dataset_artifacts', 'dataset_version_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dataset_artifacts', sa.Column(
        'dataset_version_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('dataset_artifacts', sa.Column('artifact_type', postgresql.ENUM(
        'DATA', 'SCHEMA', 'STATS', 'PREVIEW', 'FEATURES', name='artifacttype'), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('fk_dataset_artifacts_dataset_version_id_dataset_versions'),
                          'dataset_artifacts', 'dataset_versions', ['dataset_version_id'], ['id'])
    op.drop_constraint(op.f('uq_dataset_artifacts_checksum'),
                       'dataset_artifacts', type_='unique')
    op.drop_index('idx_dataset_version_artifacts_latest',
                  table_name='dataset_version_artifacts', postgresql_where=sa.text('is_latest = true'))
    op.drop_index('idx_dataset_version_artifacts_is_latest',
                  table_name='dataset_version_artifacts')
    op.drop_index('idx_dataset_version_artifacts_id_version',
                  table_name='dataset_version_artifacts')
    op.drop_table('dataset_version_artifacts')
    # ### end Alembic commands ###
