"""updates users and owners relation

Revision ID: 39e966696ab0
Revises: a78e4038c59f
Create Date: 2026-03-05 19:14:43.028111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39e966696ab0'
down_revision: Union[str, Sequence[str], None] = 'a78e4038c59f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('owners', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_unique_constraint("uq_owners_user_id", 'owners', ['user_id'])
    op.create_foreign_key("fk_owners_user_id_users",
                          'owners', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_owners_user_id_users", 'owners', type_='foreignkey')
    op.drop_constraint(constraint_name="uq_owners_user_id",
                       table_name='owners', type_='unique')
    op.drop_column('owners', 'user_id')
    # ### end Alembic commands ###
