"""removes row_count and column_count from dataset version entity

Revision ID: 47f32ecfefe6
Revises: 6db109c63b0b
Create Date: 2026-03-08 14:23:59.752201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47f32ecfefe6'
down_revision: Union[str, Sequence[str], None] = '6db109c63b0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dataset_versions', 'column_count')
    op.drop_column('dataset_versions', 'row_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dataset_versions', sa.Column('row_count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('dataset_versions', sa.Column('column_count', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
