"""adds frequency for distribution clauses

Revision ID: 4a85e85e402e
Revises: a4900d4b8611
Create Date: 2026-04-12 22:59:45.262620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a85e85e402e'
down_revision: Union[str, Sequence[str], None] = 'a4900d4b8611'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inference_results', sa.Column('frequency', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inference_results', 'frequency')
    # ### end Alembic commands ###
