"""removes model.version property

Revision ID: 4d69b118d5b4
Revises: bfe8a2c354c2
Create Date: 2026-02-14 14:01:02.895722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d69b118d5b4'
down_revision: Union[str, Sequence[str], None] = 'bfe8a2c354c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('models', 'version')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('models', sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
