"""adds jobs and job versions

Revision ID: 5cd7031d8755
Revises: ec42e97599f3
Create Date: 2026-03-15 13:31:41.156220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5cd7031d8755'
down_revision: Union[str, Sequence[str], None] = 'ec42e97599f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

loss_func_enum = sa.Enum('MSE', 'GAUSSIAN', 'BERNOULLI',
                         'POISSON', name='lossfunction')


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_versions',
                    sa.Column('job_id', sa.UUID(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('dataset_artifact_id',
                              sa.UUID(), nullable=False),
                    sa.Column('generations', sa.Integer(), nullable=False),
                    sa.Column('population', sa.Integer(), nullable=False),
                    sa.Column('max_size', sa.Integer(), nullable=False),
                    sa.Column('number_of_tournaments',
                              sa.Integer(), nullable=False),
                    sa.Column('crossover_probability',
                              sa.Float(), nullable=False),
                    sa.Column('mutation_probability',
                              sa.Float(), nullable=False),
                    sa.Column('non_terminals', sa.String(), nullable=False),
                    sa.Column('loss', loss_func_enum, nullable=False),
                    sa.Column('optimization_iterations',
                              sa.Integer(), nullable=False),
                    sa.Column('optimization_repeats',
                              sa.Integer(), nullable=False),
                    sa.Column('max_param_count', sa.Integer(), nullable=False),
                    sa.Column('split', sa.Integer(), nullable=False),
                    sa.Column('simplify', sa.Boolean(), nullable=False),
                    sa.Column('id', sa.UUID(), server_default=sa.text(
                        'gen_random_uuid()'), nullable=False),
                    sa.Column('version', sa.Integer(), nullable=False),
                    sa.Column('is_latest', sa.Boolean(), nullable=False),
                    sa.Column('timestamp', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.ForeignKeyConstraint(['dataset_artifact_id'], ['dataset_artifacts.id'], name=op.f(
                        'fk_job_versions_dataset_artifact_id_dataset_artifacts')),
                    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f(
                        'fk_job_versions_job_id_jobs')),
                    sa.PrimaryKeyConstraint(
                        'id', name=op.f('pk_job_versions')),
                    sa.UniqueConstraint(
                        'id', 'version', name='uq_job_versions_id_version')
                    )
    op.create_index('idx_job_versions_id_version', 'job_versions', [
                    'id', 'version'], unique=False)
    op.create_index('idx_job_versions_is_latest',
                    'job_versions', ['is_latest'], unique=False)
    op.create_index('idx_job_versions_latest', 'job_versions', [
                    'id'], unique=True, postgresql_where=sa.text('is_latest = true'))
    op.add_column('jobs', sa.Column('owner_id', sa.UUID(), nullable=False))
    op.add_column('jobs', sa.Column('created_at', sa.DateTime(
        timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('jobs', sa.Column('updated_at', sa.DateTime(
        timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_index(op.f('idx_jobs_id_version'), table_name='jobs')
    op.drop_index(op.f('idx_jobs_is_latest'), table_name='jobs')
    op.drop_index(op.f('idx_jobs_latest'), table_name='jobs',
                  postgresql_where='(is_latest = true)')
    op.drop_constraint(op.f('uq_jobs_id_version'), 'jobs', type_='unique')
    op.drop_constraint(op.f(
        'fk_jobs_dataset_artifact_id_dataset_artifacts'), 'jobs', type_='foreignkey')
    op.create_foreign_key(op.f('fk_jobs_owner_id_owners'),
                          'jobs', 'owners', ['owner_id'], ['id'])
    op.drop_column('jobs', 'non_terminals')
    op.drop_column('jobs', 'version')
    op.drop_column('jobs', 'population')
    op.drop_column('jobs', 'loss')
    op.drop_column('jobs', 'max_param_count')
    op.drop_column('jobs', 'timestamp')
    op.drop_column('jobs', 'name')
    op.drop_column('jobs', 'number_of_tournaments')
    op.drop_column('jobs', 'generations')
    op.drop_column('jobs', 'dataset_artifact_id')
    op.drop_column('jobs', 'is_latest')
    op.drop_column('jobs', 'simplify')
    op.drop_column('jobs', 'max_size')
    op.drop_column('jobs', 'mutation_probability')
    op.drop_column('jobs', 'optimization_repeats')
    op.drop_column('jobs', 'optimization_iterations')
    op.drop_column('jobs', 'split')
    op.drop_column('jobs', 'crossover_probability')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('crossover_probability', sa.DOUBLE_PRECISION(
        precision=53), autoincrement=False, nullable=False))
    op.add_column('jobs', sa.Column('split', sa.INTEGER(),
                  autoincrement=False, nullable=False))
    op.add_column('jobs', sa.Column('optimization_iterations',
                  sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('jobs', sa.Column('optimization_repeats',
                  sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('jobs', sa.Column('mutation_probability', sa.DOUBLE_PRECISION(
        precision=53), autoincrement=False, nullable=False))
    op.add_column('jobs', sa.Column('max_size', sa.INTEGER(),
                  autoincrement=False, nullable=False))
    op.add_column('jobs', sa.Column('simplify', sa.BOOLEAN(),
                  autoincrement=False, nullable=False))
    op.add_column('jobs', sa.Column('is_latest', sa.BOOLEAN(),
                  autoincrement=False, nullable=False))
    op.add_column('jobs', sa.Column('dataset_artifact_id',
                  sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('jobs', sa.Column('generations', sa.INTEGER(),
                  autoincrement=False, nullable=False))
    op.add_column('jobs', sa.Column('number_of_tournaments',
                  sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('jobs', sa.Column('name', sa.VARCHAR(),
                  autoincrement=False, nullable=False))
    op.add_column('jobs', sa.Column('timestamp', postgresql.TIMESTAMP(
        timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('jobs', sa.Column('max_param_count',
                  sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('jobs', sa.Column('loss', postgresql.ENUM('MSE', 'GAUSSIAN', 'BERNOULLI',
                  'POISSON', name='lossfunction'), autoincrement=False, nullable=False))
    op.add_column('jobs', sa.Column('population', sa.INTEGER(),
                  autoincrement=False, nullable=False))
    op.add_column('jobs', sa.Column('version', sa.INTEGER(),
                  autoincrement=False, nullable=False))
    op.add_column('jobs', sa.Column('non_terminals', sa.VARCHAR(),
                  autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk_jobs_owner_id_owners'),
                       'jobs', type_='foreignkey')
    op.create_foreign_key(op.f('fk_jobs_dataset_artifact_id_dataset_artifacts'),
                          'jobs', 'dataset_artifacts', ['dataset_artifact_id'], ['id'])
    op.create_unique_constraint(op.f('uq_jobs_id_version'), 'jobs', [
                                'id', 'version'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_jobs_latest'), 'jobs', [
                    'id'], unique=True, postgresql_where='(is_latest = true)')
    op.create_index(op.f('idx_jobs_is_latest'), 'jobs',
                    ['is_latest'], unique=False)
    op.create_index(op.f('idx_jobs_id_version'), 'jobs',
                    ['id', 'version'], unique=False)
    op.drop_column('jobs', 'updated_at')
    op.drop_column('jobs', 'created_at')
    op.drop_column('jobs', 'owner_id')
    op.drop_index('idx_job_versions_latest', table_name='job_versions',
                  postgresql_where=sa.text('is_latest = true'))
    op.drop_index('idx_job_versions_is_latest', table_name='job_versions')
    op.drop_index('idx_job_versions_id_version', table_name='job_versions')
    op.drop_table('job_versions')
    # ### end Alembic commands ###
