"""adds job run model

Revision ID: 72217dc2bbb9
Revises: 1bdf5f171ee0
Create Date: 2026-03-18 22:54:40.444674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72217dc2bbb9'
down_revision: Union[str, Sequence[str], None] = '1bdf5f171ee0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_runs',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('job_run_status', sa.Enum('QUEUED', 'WAITING', 'RUNNING', 'SUCCESSFUL', 'FAILED', 'KILLED', 'DELETED', name='jobrunstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_job_runs_job_id_jobs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_runs')),
    sa.UniqueConstraint('id', name='uq_job_runs_id')
    )
    op.create_index('idx_job_runs_timestamp', 'job_runs', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_job_runs_timestamp', table_name='job_runs')
    op.drop_table('job_runs')
    # ### end Alembic commands ###
