"""adds num_rows and num_features properties to dataset

Revision ID: 837776541461
Revises: 531e391b90c3
Create Date: 2026-02-01 19:21:05.457245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '837776541461'
down_revision: Union[str, Sequence[str], None] = '531e391b90c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datasets', sa.Column('num_rows', sa.Integer(), nullable=True))
    op.add_column('datasets', sa.Column('num_features', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('datasets', 'num_features')
    op.drop_column('datasets', 'num_rows')
    # ### end Alembic commands ###
