"""adds profiles, profile_versions and profile_version_dataset_associations

Revision ID: 8d96f7204c5a
Revises: 932ceb323ce9
Create Date: 2026-03-11 20:36:24.621202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8d96f7204c5a'
down_revision: Union[str, Sequence[str], None] = '932ceb323ce9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile_versions',
                    sa.Column('profile_id', sa.UUID(), nullable=False),
                    sa.Column('id', sa.UUID(), server_default=sa.text(
                        'gen_random_uuid()'), nullable=False),
                    sa.Column('version', sa.Integer(), nullable=False),
                    sa.Column('is_latest', sa.Boolean(), nullable=False),
                    sa.Column('timestamp', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name=op.f(
                        'fk_profile_versions_profile_id_profiles')),
                    sa.PrimaryKeyConstraint(
                        'id', name=op.f('pk_profile_versions')),
                    sa.UniqueConstraint(
                        'id', 'version', name='uq_profile_versions_id_version')
                    )
    op.create_index('idx_profile_versions_id_version',
                    'profile_versions', ['id', 'version'], unique=False)
    op.create_index('idx_profile_versions_is_latest',
                    'profile_versions', ['is_latest'], unique=False)
    op.create_index('idx_profile_versions_latest', 'profile_versions', [
                    'id'], unique=True, postgresql_where=sa.text('is_latest = true'))
    op.create_table('profile_dataset_associations',
                    sa.Column('profile_version_id', sa.UUID(), nullable=False),
                    sa.Column('dataset_version_id', sa.UUID(), nullable=False),
                    sa.Column('role', sa.Enum('TRAINING', 'TESTING', 'VALIDATING',
                                              name='profiledatasetrole'), nullable=False),
                    sa.Column('id', sa.UUID(), server_default=sa.text(
                        'gen_random_uuid()'), nullable=False),
                    sa.Column('timestamp', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.ForeignKeyConstraint(['dataset_version_id'], ['dataset_versions.id'], name=op.f(
                        'fk_profile_dataset_associations_dataset_version_id_dataset_versions')),
                    sa.ForeignKeyConstraint(['profile_version_id'], ['profile_versions.id'], name=op.f(
                        'fk_profile_dataset_associations_profile_version_id_profile_versions')),
                    sa.PrimaryKeyConstraint('id', name=op.f(
                        'pk_profile_dataset_associations')),
                    sa.UniqueConstraint(
                        'id', name='uq_profile_dataset_associations_id')
                    )
    op.create_index('idx_profile_dataset_associations_timestamp',
                    'profile_dataset_associations', ['timestamp'], unique=False)
    op.drop_index(op.f('idx_profile_dataset_versions_id_version'),
                  table_name='profile_dataset_versions')
    op.drop_index(op.f('idx_profile_dataset_versions_is_latest'),
                  table_name='profile_dataset_versions')
    op.drop_index(op.f('idx_profile_dataset_versions_latest'),
                  table_name='profile_dataset_versions', postgresql_where='(is_latest = true)')
    op.drop_index(op.f('ix_profile_dataset_versions_dataset_version_id'),
                  table_name='profile_dataset_versions')
    op.drop_index(op.f('ix_profile_dataset_versions_profile_id'),
                  table_name='profile_dataset_versions')
    op.drop_table('profile_dataset_versions')
    op.add_column('profiles', sa.Column('created_at', sa.DateTime(
        timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('profiles', sa.Column('updated_at', sa.DateTime(
        timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_index(op.f('idx_profiles_id_version'), table_name='profiles')
    op.drop_index(op.f('idx_profiles_is_latest'), table_name='profiles')
    op.drop_index(op.f('idx_profiles_latest'), table_name='profiles',
                  postgresql_where='(is_latest = true)')
    op.drop_index(op.f('ix_profiles_owner_id'), table_name='profiles')
    op.drop_index(op.f('ix_profiles_owner_visibility'), table_name='profiles')
    op.drop_index(op.f('ix_profiles_status'), table_name='profiles')
    op.drop_index(op.f('ix_profiles_visibility'), table_name='profiles')
    op.drop_constraint(op.f('uq_profiles_id_version'),
                       'profiles', type_='unique')
    op.drop_constraint(op.f('fk_profiles_owner_id_owners'),
                       'profiles', type_='foreignkey')
    op.create_foreign_key(op.f('fk_profiles_owner_id_owners'),
                          'profiles', 'owners', ['owner_id'], ['id'])
    op.drop_column('profiles', 'is_latest')
    op.drop_column('profiles', 'version')
    op.drop_column('profiles', 'timestamp')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('timestamp', postgresql.TIMESTAMP(
        timezone=True), autoincrement=False, nullable=False))
    op.add_column('profiles', sa.Column('version', sa.INTEGER(),
                  autoincrement=False, nullable=False))
    op.add_column('profiles', sa.Column(
        'is_latest', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk_profiles_owner_id_owners'),
                       'profiles', type_='foreignkey')
    op.create_foreign_key(op.f('fk_profiles_owner_id_owners'), 'profiles', 'owners', [
                          'owner_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(op.f('uq_profiles_id_version'), 'profiles', [
                                'id', 'version'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_profiles_visibility'),
                    'profiles', ['visibility'], unique=False)
    op.create_index(op.f('ix_profiles_status'),
                    'profiles', ['status'], unique=False)
    op.create_index(op.f('ix_profiles_owner_visibility'), 'profiles', [
                    'owner_id', 'visibility'], unique=False)
    op.create_index(op.f('ix_profiles_owner_id'),
                    'profiles', ['owner_id'], unique=False)
    op.create_index(op.f('idx_profiles_latest'), 'profiles', [
                    'id'], unique=True, postgresql_where='(is_latest = true)')
    op.create_index(op.f('idx_profiles_is_latest'),
                    'profiles', ['is_latest'], unique=False)
    op.create_index(op.f('idx_profiles_id_version'),
                    'profiles', ['id', 'version'], unique=False)
    op.alter_column('profiles', 'visibility',
                    existing_type=sa.Enum(
                        'PUBLIC', 'PRIVATE', name='profilevisibility'),
                    type_=postgresql.ENUM(
                        'PUBLIC', 'PRIVATE', name='profile_visibility'),
                    existing_nullable=False)
    op.alter_column('profiles', 'status',
                    existing_type=sa.Enum(
                        'ACTIVE', 'INACTIVE', 'DELETED', name='profilestatus'),
                    type_=postgresql.ENUM(
                        'ACTIVE', 'INACTIVE', 'DELETED', name='profile_status'),
                    existing_nullable=False)
    op.drop_column('profiles', 'updated_at')
    op.drop_column('profiles', 'created_at')
    op.create_table('profile_dataset_versions',
                    sa.Column('profile_id', sa.UUID(),
                              autoincrement=False, nullable=False),
                    sa.Column('dataset_version_id', sa.UUID(),
                              autoincrement=False, nullable=False),
                    sa.Column('role', postgresql.ENUM('TRAINING', 'TESTING', 'VALIDATING',
                                                      name='profile_dataset_role'), autoincrement=False, nullable=False),
                    sa.Column('id', sa.UUID(), server_default=sa.text(
                        'gen_random_uuid()'), autoincrement=False, nullable=False),
                    sa.Column('version', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.Column('is_latest', sa.BOOLEAN(),
                              autoincrement=False, nullable=False),
                    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), server_default=sa.text(
                        'now()'), autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(['dataset_version_id'], ['dataset_versions.id'], name=op.f(
                        'fk_profile_dataset_versions_dataset_version_id_dataset_versions'), ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name=op.f(
                        'fk_profile_dataset_versions_profile_id_profiles'), ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('profile_id', 'dataset_version_id', name=op.f(
                        'pk_profile_dataset_versions')),
                    sa.UniqueConstraint('id', 'version', name=op.f(
                        'uq_profile_dataset_versions_id_version'), postgresql_include=[], postgresql_nulls_not_distinct=False)
                    )
    op.create_index(op.f('ix_profile_dataset_versions_profile_id'),
                    'profile_dataset_versions', ['profile_id'], unique=False)
    op.create_index(op.f('ix_profile_dataset_versions_dataset_version_id'),
                    'profile_dataset_versions', ['dataset_version_id'], unique=False)
    op.create_index(op.f('idx_profile_dataset_versions_latest'), 'profile_dataset_versions', [
                    'id'], unique=True, postgresql_where='(is_latest = true)')
    op.create_index(op.f('idx_profile_dataset_versions_is_latest'),
                    'profile_dataset_versions', ['is_latest'], unique=False)
    op.create_index(op.f('idx_profile_dataset_versions_id_version'),
                    'profile_dataset_versions', ['id', 'version'], unique=False)
    op.drop_index('idx_profile_dataset_associations_timestamp',
                  table_name='profile_dataset_associations')
    op.drop_table('profile_dataset_associations')
    op.drop_index('idx_profile_versions_latest', table_name='profile_versions',
                  postgresql_where=sa.text('is_latest = true'))
    op.drop_index('idx_profile_versions_is_latest',
                  table_name='profile_versions')
    op.drop_index('idx_profile_versions_id_version',
                  table_name='profile_versions')
    op.drop_table('profile_versions')
    # ### end Alembic commands ###
