"""removes versioned properties from DatasetArtifact

Revision ID: 932ceb323ce9
Revises: 6ab2184bde66
Create Date: 2026-03-08 21:37:50.998046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '932ceb323ce9'
down_revision: Union[str, Sequence[str], None] = '6ab2184bde66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_dataset_artifacts_id_version'), table_name='dataset_artifacts')
    op.drop_index(op.f('idx_dataset_artifacts_is_latest'), table_name='dataset_artifacts')
    op.drop_index(op.f('idx_dataset_artifacts_latest'), table_name='dataset_artifacts', postgresql_where='(is_latest = true)')
    op.drop_constraint(op.f('uq_dataset_artifacts_id_version'), 'dataset_artifacts', type_='unique')
    op.create_index('idx_dataset_artifacts_timestamp', 'dataset_artifacts', ['timestamp'], unique=False)
    op.create_unique_constraint('uq_dataset_artifacts_id', 'dataset_artifacts', ['id'])
    op.drop_column('dataset_artifacts', 'version')
    op.drop_column('dataset_artifacts', 'is_latest')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dataset_artifacts', sa.Column('is_latest', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('dataset_artifacts', sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint('uq_dataset_artifacts_id', 'dataset_artifacts', type_='unique')
    op.drop_index('idx_dataset_artifacts_timestamp', table_name='dataset_artifacts')
    op.create_unique_constraint(op.f('uq_dataset_artifacts_id_version'), 'dataset_artifacts', ['id', 'version'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_dataset_artifacts_latest'), 'dataset_artifacts', ['id'], unique=True, postgresql_where='(is_latest = true)')
    op.create_index(op.f('idx_dataset_artifacts_is_latest'), 'dataset_artifacts', ['is_latest'], unique=False)
    op.create_index(op.f('idx_dataset_artifacts_id_version'), 'dataset_artifacts', ['id', 'version'], unique=False)
    # ### end Alembic commands ###
