"""moves name and description to DatasetVersion

Revision ID: 96b282be92ec
Revises: e970773499f5
Create Date: 2026-03-14 16:33:18.105935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96b282be92ec'
down_revision: Union[str, Sequence[str], None] = 'e970773499f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dataset_versions', sa.Column('name', sa.String(length=255), nullable=False))
    op.add_column('dataset_versions', sa.Column('description', sa.String(length=255), nullable=True))
    op.drop_column('datasets', 'name')
    op.drop_column('datasets', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datasets', sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('datasets', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('dataset_versions', 'description')
    op.drop_column('dataset_versions', 'name')
    # ### end Alembic commands ###
