"""adds job model

Revision ID: 9ac3f8ec3b0c
Revises:
Create Date: 2026-02-01 14:32:50.821414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from app.domain.jobs.job_status import JobStatus


# revision identifiers, used by Alembic.
revision: str = '9ac3f8ec3b0c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

job_status_enum = sa.Enum(
    JobStatus,
    name="job_status"
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('status', job_status_enum, nullable=False,
                              default=JobStatus.PENDING.value),
                    sa.Column('dataset_id', sa.UUID(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('started_at', sa.DateTime(
                        timezone=True), nullable=True),
                    sa.Column('finished_at', sa.DateTime(
                        timezone=True), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jobs')
    job_status_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
