"""adds model parameters into job

Revision ID: a3ee514115bb
Revises: 4d69b118d5b4
Create Date: 2026-02-14 23:18:11.464867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3ee514115bb'
down_revision: Union[str, Sequence[str], None] = '4d69b118d5b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


loss_enum = sa.Enum('MSE', 'GAUSSIAN', 'BERNOULLI',
                    'POISSON', name='loss_function')


def upgrade() -> None:
    loss_enum.create(op.get_bind(), checkfirst=True)

    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column(
        'generations', sa.Integer(), nullable=False))
    op.add_column('jobs', sa.Column(
        'population', sa.Integer(), nullable=False))
    op.add_column('jobs', sa.Column('max_size', sa.Integer(), nullable=False))
    op.add_column('jobs', sa.Column(
        'number_of_tournaments', sa.Integer(), nullable=False))
    op.add_column('jobs', sa.Column(
        'crossover_probability', sa.Float(), nullable=False))
    op.add_column('jobs', sa.Column(
        'mutation_probability', sa.Float(), nullable=False))
    op.add_column('jobs', sa.Column(
        'non_terminals', sa.String(), nullable=False))
    op.add_column('jobs', sa.Column('loss', loss_enum, nullable=False))
    op.add_column('jobs', sa.Column(
        'optimization_iterations', sa.Integer(), nullable=False))
    op.add_column('jobs', sa.Column(
        'optimization_repeats', sa.Integer(), nullable=False))
    op.add_column('jobs', sa.Column(
        'max_param_count', sa.Integer(), nullable=False))
    op.add_column('jobs', sa.Column('split', sa.Integer(), nullable=False))
    op.add_column('jobs', sa.Column('simplify', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'simplify')
    op.drop_column('jobs', 'split')
    op.drop_column('jobs', 'max_param_count')
    op.drop_column('jobs', 'optimization_repeats')
    op.drop_column('jobs', 'optimization_iterations')
    op.drop_column('jobs', 'loss')
    op.drop_column('jobs', 'non_terminals')
    op.drop_column('jobs', 'mutation_probability')
    op.drop_column('jobs', 'crossover_probability')
    op.drop_column('jobs', 'number_of_tournaments')
    op.drop_column('jobs', 'max_size')
    op.drop_column('jobs', 'population')
    op.drop_column('jobs', 'generations')

    loss_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
