"""adds owners and profiles

Revision ID: a78e4038c59f
Revises: e9459725d582
Create Date: 2026-03-05 18:47:36.823277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a78e4038c59f'
down_revision: Union[str, Sequence[str], None] = 'e9459725d582'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('owners',
    sa.Column('owner_type', sa.Enum('USER', 'TEAM', 'ORGANIZATION', name='owner_type'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_latest', sa.Boolean(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'version', name='uq_owners_id_version')
    )
    op.create_index('idx_owners_id_version', 'owners', ['id', 'version'], unique=False)
    op.create_index('idx_owners_is_latest', 'owners', ['is_latest'], unique=False)
    op.create_table('profiles',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('dataset_file_path', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'DELETED', name='profile_status'), nullable=False),
    sa.Column('visibility', sa.Enum('PUBLIC', 'PRIVATE', name='profile_visibility'), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_latest', sa.Boolean(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'version', name='uq_profiles_id_version')
    )
    op.create_index('idx_profiles_id_version', 'profiles', ['id', 'version'], unique=False)
    op.create_index('idx_profiles_is_latest', 'profiles', ['is_latest'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_profiles_is_latest', table_name='profiles')
    op.drop_index('idx_profiles_id_version', table_name='profiles')
    op.drop_table('profiles')
    op.drop_index('idx_owners_is_latest', table_name='owners')
    op.drop_index('idx_owners_id_version', table_name='owners')
    op.drop_table('owners')
    # ### end Alembic commands ###
