"""adds model_file property to Model table

Revision ID: a817ae454ad5
Revises: f06945eb7a55
Create Date: 2026-02-03 14:16:19.766887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a817ae454ad5'
down_revision: Union[str, Sequence[str], None] = 'f06945eb7a55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('models', sa.Column('model_file', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('models', 'model_file')
    # ### end Alembic commands ###
