"""updates inference run table to have status and execution time properties

Revision ID: aa89d6033d76
Revises: 7c903da29148
Create Date: 2026-04-05 15:27:13.527569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aa89d6033d76'
down_revision: Union[str, Sequence[str], None] = '7c903da29148'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inference_runs',
    sa.Column('block_id', sa.UUID(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('query', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RESOLVING_MODELS', 'DOWNLOADING_DATA', 'EXECUTING', 'COMPLETED', 'FAILED', name='inferencerunstatus'), nullable=False),
    sa.Column('execution_time_ms', sa.Integer(), nullable=True),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_latest', sa.Boolean(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['block_id'], ['blocks.id'], name=op.f('fk_inference_runs_block_id_blocks'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name=op.f('fk_inference_runs_profile_id_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'version', name=op.f('pk_inference_runs')),
    sa.UniqueConstraint('id', 'version', name='uq_inference_runs_id_version')
    )
    op.create_index('idx_inference_runs_id_version', 'inference_runs', ['id', 'version'], unique=False)
    op.create_index('idx_inference_runs_is_latest', 'inference_runs', ['is_latest'], unique=False)
    op.create_index('idx_inference_runs_latest', 'inference_runs', ['id'], unique=True, postgresql_where=sa.text('is_latest = true'))
    op.create_table('inference_results',
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('run_version', sa.Integer(), nullable=False),
    sa.Column('expression', sa.String(), nullable=False),
    sa.Column('dl', sa.Float(), nullable=True),
    sa.Column('fitness', sa.Float(), nullable=True),
    sa.Column('latex', sa.String(), nullable=True),
    sa.Column('numpy', sa.String(), nullable=True),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id', 'run_version'], ['inference_runs.id', 'inference_runs.version'], name=op.f('fk_inference_results_run_id_inference_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inference_results')),
    sa.UniqueConstraint('id', name='uq_inference_results_id')
    )
    op.create_index('idx_inference_results_timestamp', 'inference_results', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_inference_results_timestamp', table_name='inference_results')
    op.drop_table('inference_results')
    op.drop_index('idx_inference_runs_latest', table_name='inference_runs', postgresql_where=sa.text('is_latest = true'))
    op.drop_index('idx_inference_runs_is_latest', table_name='inference_runs')
    op.drop_index('idx_inference_runs_id_version', table_name='inference_runs')
    op.drop_table('inference_runs')
    # ### end Alembic commands ###
