"""adds relationship between model and job

Revision ID: bfe8a2c354c2
Revises: 1b4c0c121141
Create Date: 2026-02-09 23:14:41.344960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfe8a2c354c2'
down_revision: Union[str, Sequence[str], None] = '1b4c0c121141'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('models', sa.Column('job_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'models', 'jobs', ['job_id'], [
                          'id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'models', type_='foreignkey')  # type: ignore
    op.drop_column('models', 'job_id')
    # ### end Alembic commands ###
