"""adds deleted_at property to owners table

Revision ID: e863ebe1ac4f
Revises: b9f9027260a4
Create Date: 2026-03-05 20:24:26.973316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e863ebe1ac4f'
down_revision: Union[str, Sequence[str], None] = 'b9f9027260a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('owners', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('owners', 'deleted_at')
    # ### end Alembic commands ###
