"""adds ProfileBlockORM model

Revision ID: e970773499f5
Revises: 7b55fae53070
Create Date: 2026-03-14 14:16:05.810315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e970773499f5'
down_revision: Union[str, Sequence[str], None] = '7b55fae53070'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile_blocks',
    sa.Column('version_id', sa.UUID(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('INFERENCE', 'MARKDOWN', name='profileblocktype'), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['version_id'], ['profile_versions.id'], name=op.f('fk_profile_blocks_version_id_profile_versions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_profile_blocks'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profile_blocks')
    # ### end Alembic commands ###
