"""adds jobs table

Revision ID: ec42e97599f3
Revises: 96b282be92ec
Create Date: 2026-03-15 00:23:45.541900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec42e97599f3'
down_revision: Union[str, Sequence[str], None] = '96b282be92ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('profile_version_id', sa.UUID(), nullable=False),
    sa.Column('dataset_artifact_id', sa.UUID(), nullable=False),
    sa.Column('generations', sa.Integer(), nullable=False),
    sa.Column('population', sa.Integer(), nullable=False),
    sa.Column('max_size', sa.Integer(), nullable=False),
    sa.Column('number_of_tournaments', sa.Integer(), nullable=False),
    sa.Column('crossover_probability', sa.Float(), nullable=False),
    sa.Column('mutation_probability', sa.Float(), nullable=False),
    sa.Column('non_terminals', sa.String(), nullable=False),
    sa.Column('loss', sa.Enum('MSE', 'GAUSSIAN', 'BERNOULLI', 'POISSON', name='lossfunction'), nullable=False),
    sa.Column('optimization_iterations', sa.Integer(), nullable=False),
    sa.Column('optimization_repeats', sa.Integer(), nullable=False),
    sa.Column('max_param_count', sa.Integer(), nullable=False),
    sa.Column('split', sa.Integer(), nullable=False),
    sa.Column('simplify', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_latest', sa.Boolean(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dataset_artifact_id'], ['dataset_artifacts.id'], name=op.f('fk_jobs_dataset_artifact_id_dataset_artifacts')),
    sa.ForeignKeyConstraint(['profile_version_id'], ['profile_versions.id'], name=op.f('fk_jobs_profile_version_id_profile_versions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jobs')),
    sa.UniqueConstraint('id', 'version', name='uq_jobs_id_version')
    )
    op.create_index('idx_jobs_id_version', 'jobs', ['id', 'version'], unique=False)
    op.create_index('idx_jobs_is_latest', 'jobs', ['is_latest'], unique=False)
    op.create_index('idx_jobs_latest', 'jobs', ['id'], unique=True, postgresql_where=sa.text('is_latest = true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_jobs_latest', table_name='jobs', postgresql_where=sa.text('is_latest = true'))
    op.drop_index('idx_jobs_is_latest', table_name='jobs')
    op.drop_index('idx_jobs_id_version', table_name='jobs')
    op.drop_table('jobs')
    # ### end Alembic commands ###
