import { useState } from "react";
import { Copy, Layers, BarChart2 } from "lucide-react";
import { toast } from "sonner";
import type { Model } from "~/schemas/domain/model.schema";
import { ModelInsights } from "./model-insights.component";

type ModelItemProps = {
	model: Model;
	jobName: string;
};

export function ModelItem({ model, jobName }: ModelItemProps) {
	const [showInsights, setShowInsights] = useState(false);

	const copyToClipboard = () => {
		navigator.clipboard.writeText(model.id);
		toast.success("Model ID copied to clipboard");
	};

	return (
		<>
			<div className="border border-border rounded-md p-3 bg-white/5 transition-colors group">
				<div className="flex items-start justify-between gap-4">
					<div className="flex items-center gap-3">
						<div className="p-2 bg-primary/10 rounded-lg text-primary-500">
							<Layers size={18} />
						</div>
						<div className="flex flex-col gap-1">
							<h3 className="font-bold text-sm text-foreground leading-tight">
								{model.name}
							</h3>
							<p className="text-[8px] text-gray-500 uppercase tracking-wider font-medium">
								Generated by{" "}
								<span className="text-primary-foreground/70">{jobName}</span>
							</p>
						</div>
					</div>

					<div className="flex items-center gap-2">
						<button
							type="button"
							onClick={() => setShowInsights(true)}
							className="p-1.5 hover:bg-white/10 rounded-md text-primary-400 hover:text-primary-300 transition-all flex items-center gap-1.5 cursor-pointer"
							title="View Model Insights"
						>
							<BarChart2 size={14} />
						</button>

						<button
							type="button"
							onClick={copyToClipboard}
							className="p-1.5 hover:bg-white/10 rounded-md text-muted-foreground hover:text-foreground transition-all flex items-center gap-1.5 cursor-pointer"
							title="Copy Model Name"
						>
							<Copy size={14} />
						</button>
					</div>
				</div>
			</div>

			{showInsights && (
				<ModelInsights model={model} onClose={() => setShowInsights(false)} />
			)}
		</>
	);
}
