"""Adds eggp_file_path to Job Runs Table

Revision ID: 7f2f13059502
Revises: 24d0484cd9fd
Create Date: 2025-08-21 23:50:12.290375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7f2f13059502'
down_revision: Union[str, Sequence[str], None] = '24d0484cd9fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        'job_runs',
        sa.Column(
            'eggp_file_path',
            sa.String,
            nullable=True,
            comment='Path to the EGGP file generated by the model training'
        )
    )


def downgrade() -> None:
    op.drop_column('job_runs', 'eggp_file_path')
