"""starts all tables

Revision ID: 00f7ec1f25a2
Revises: d183db04ffae
Create Date: 2026-03-21 21:34:44.310986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00f7ec1f25a2'
down_revision: Union[str, Sequence[str], None] = 'd183db04ffae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('runs_against', sa.UUID(), nullable=False),
    sa.Column('generations', sa.Integer(), nullable=False),
    sa.Column('population', sa.Integer(), nullable=False),
    sa.Column('max_size', sa.Integer(), nullable=False),
    sa.Column('number_of_tournaments', sa.Integer(), nullable=False),
    sa.Column('crossover_probability', sa.Float(), nullable=False),
    sa.Column('mutation_probability', sa.Float(), nullable=False),
    sa.Column('non_terminals', sa.String(), nullable=False),
    sa.Column('loss', sa.Enum('MSE', 'GAUSSIAN', 'BERNOULLI', 'POISSON', name='lossfunction'), nullable=False),
    sa.Column('optimization_iterations', sa.Integer(), nullable=False),
    sa.Column('optimization_repeats', sa.Integer(), nullable=False),
    sa.Column('max_param_count', sa.Integer(), nullable=False),
    sa.Column('split', sa.Integer(), nullable=False),
    sa.Column('simplify', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jobs'))
    )
    op.create_table('datasets',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_datasets_owner_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_datasets'))
    )
    op.create_table('profiles',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('mode', sa.Enum('DRAFT', 'RELEASED', 'ARCHIVED', name='profilemode'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_profiles_owner_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_profiles'))
    )
    op.create_table('runs',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('WAITING', 'RUNNING', 'FINISHED', 'FAILED', name='jobrunstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_latest', sa.Boolean(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_runs_job_id_jobs')),
    sa.PrimaryKeyConstraint('id', 'version', name=op.f('pk_runs')),
    sa.UniqueConstraint('id', 'version', name='uq_runs_id_version')
    )
    op.create_index('idx_runs_id_version', 'runs', ['id', 'version'], unique=False)
    op.create_index('idx_runs_is_latest', 'runs', ['is_latest'], unique=False)
    op.create_index('idx_runs_latest', 'runs', ['id'], unique=True, postgresql_where=sa.text('is_latest = true'))
    op.create_table('artifacts',
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('checksum', sa.String(), nullable=False),
    sa.Column('size_in_bytes', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('DATA', 'VALIDATION', name='artifactrole'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], name=op.f('fk_artifacts_dataset_id_datasets')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_artifacts')),
    sa.UniqueConstraint('id', name='uq_artifacts_id')
    )
    op.create_index('idx_artifacts_timestamp', 'artifacts', ['timestamp'], unique=False)
    op.create_table('blocks',
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Enum('MARKDOWN', 'INFERENCE', name='blockkind'), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name=op.f('fk_blocks_profile_id_profiles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_blocks'))
    )
    op.create_table('models',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('generated_by', sa.UUID(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['generated_by'], ['jobs.id'], name=op.f('fk_models_generated_by_jobs')),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name=op.f('fk_models_profile_id_profiles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_models'))
    )
    op.create_table('profiles_datasets',
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], name=op.f('fk_profiles_datasets_dataset_id_datasets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name=op.f('fk_profiles_datasets_profile_id_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_profiles_datasets')),
    sa.UniqueConstraint('id', name='uq_profiles_datasets_id')
    )
    op.create_index('idx_profiles_datasets_timestamp', 'profiles_datasets', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_profiles_datasets_timestamp', table_name='profiles_datasets')
    op.drop_table('profiles_datasets')
    op.drop_table('models')
    op.drop_table('blocks')
    op.drop_index('idx_artifacts_timestamp', table_name='artifacts')
    op.drop_table('artifacts')
    op.drop_index('idx_runs_latest', table_name='runs', postgresql_where=sa.text('is_latest = true'))
    op.drop_index('idx_runs_is_latest', table_name='runs')
    op.drop_index('idx_runs_id_version', table_name='runs')
    op.drop_table('runs')
    op.drop_table('profiles')
    op.drop_table('datasets')
    op.drop_table('jobs')
    # ### end Alembic commands ###
