"""adds post_processing_type column to job shcema

Revision ID: 337a69c5cf8c
Revises: 7dbf2c79dedb
Create Date: 2026-07-12 23:52:41.593349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '337a69c5cf8c'
down_revision: Union[str, Sequence[str], None] = '7dbf2c79dedb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('post_processing_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'post_processing_type')
    # ### end Alembic commands ###
