"""adds inference runs and inference results tables

Revision ID: 4524e9b5643f
Revises: b0c44e65cf89
Create Date: 2026-04-05 14:41:00.468881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4524e9b5643f'
down_revision: Union[str, Sequence[str], None] = 'b0c44e65cf89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
