"""adds active_group_columns in job model

Revision ID: 7dbf2c79dedb
Revises: 7f810caec572
Create Date: 2026-07-12 19:43:54.337443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7dbf2c79dedb'
down_revision: Union[str, Sequence[str], None] = '7f810caec572'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('active_group_by_columns', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'active_group_by_columns')
    # ### end Alembic commands ###
