"""adds group by columns property to DbArtifact models

Revision ID: 7f810caec572
Revises: caf713d50352
Create Date: 2026-07-12 18:18:49.692012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f810caec572'
down_revision: Union[str, Sequence[str], None] = 'caf713d50352'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artifacts', sa.Column(
        'group_by_columns', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artifacts', 'group_by_columns')
    # ### end Alembic commands ###
