"""adds relationship between inference results and blocks

Revision ID: 89ab2fb4968e
Revises: 4a85e85e402e
Create Date: 2026-04-13 00:10:39.074548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89ab2fb4968e'
down_revision: Union[str, Sequence[str], None] = '4a85e85e402e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
