"""adds metrics into model

Revision ID: a4900d4b8611
Revises: aa89d6033d76
Create Date: 2026-04-05 20:12:06.469982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a4900d4b8611'
down_revision: Union[str, Sequence[str], None] = 'aa89d6033d76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_inference_results_id', 'inference_results', ['id'])
    op.create_unique_constraint('uq_inference_runs_id_version', 'inference_runs', ['id', 'version'])
    op.add_column('models', sa.Column('validation_path', sa.String(), nullable=True))
    op.add_column('models', sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('models', 'metrics')
    op.drop_column('models', 'validation_path')
    op.drop_constraint('uq_inference_runs_id_version', 'inference_runs', type_='unique')
    op.drop_constraint('uq_inference_results_id', 'inference_results', type_='unique')
    # ### end Alembic commands ###
