"""changes JSON to JSONB in blocks

Revision ID: c6894d91c15b
Revises: 00f7ec1f25a2
Create Date: 2026-03-22 02:18:19.972306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c6894d91c15b'
down_revision: Union[str, Sequence[str], None] = '00f7ec1f25a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_artifacts_id', 'artifacts', ['id'])
    op.alter_column('blocks', 'data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.create_foreign_key(op.f('fk_jobs_runs_against_datasets'), 'jobs', 'datasets', ['runs_against'], ['id'])
    op.create_foreign_key(op.f('fk_jobs_profile_id_profiles'), 'jobs', 'profiles', ['profile_id'], ['id'])
    op.create_unique_constraint('uq_profiles_datasets_id', 'profiles_datasets', ['id'])
    op.create_unique_constraint('uq_runs_id_version', 'runs', ['id', 'version'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_runs_id_version', 'runs', type_='unique')
    op.drop_constraint('uq_profiles_datasets_id', 'profiles_datasets', type_='unique')
    op.drop_constraint(op.f('fk_jobs_profile_id_profiles'), 'jobs', type_='foreignkey')
    op.drop_constraint(op.f('fk_jobs_runs_against_datasets'), 'jobs', type_='foreignkey')
    op.alter_column('blocks', 'data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
    op.drop_constraint('uq_artifacts_id', 'artifacts', type_='unique')
    # ### end Alembic commands ###
